runtime: php72
service: api

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.7
  max_instances: 10
  min_pending_latency: 30ms # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

env_variables:
  ## Put production environment variables here.
  APP_ENV: production
  APP_DEBUG: false
  LOG_CHANNEL: stackdriver
  APP_KEY: base64:AbASrVbYtKZcq2udG+kdc3zUt0TvlQBQl4VoTFDIau4=
  APP_LOG: errorlog
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: database
  CACHE_DRIVER: database
